const AUTH_BASE_ENDPOINT = process.env.AUTH_BASE_ENDPOINT;
export const SERVERLESS_FUNCTIONS_ENDPOINT_LOGIN =
  AUTH_BASE_ENDPOINT + '/login';
export const SERVERLESS_FUNCTIONS_ENDPOINT_SIGNUP =
  AUTH_BASE_ENDPOINT + '/signup';
